apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  storageClassName: standard
  hostPath:
    path: /data/counterapp

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  storageClassName: standard
  volumeName: my-volume