apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - nodePort: 30000
    port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: my-app   

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-stateful
spec:
  serviceName: my-service
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: junwatanabe/myexample:3.0
          ports:
          - containerPort: 80
          volumeMounts:
            - name: my-volume-storage
              mountPath: /var/data
            - name: my-volume-session
              mountPath: /var/lib/php/sessions
      imagePullSecrets:
        - name: mysecret
      volumes:
        - name: my-volume-storage
          persistentVolumeClaim:
              claimName: my-volume-claim
  volumeClaimTemplates:
  - metadata:
      name: my-volume-session
    spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Mi
        storageClassName: standard
    