apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  # type: NodePort
  type: LoadBalancer
  # sessionAffinity: ClientIP
  ports:
  # - nodePort: 30000
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: my-app   

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-stateful
spec:
  replicas: 3
  serviceName: my-service
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: 842266600872.dkr.ecr.us-east-1.amazonaws.com/myexample_ecr
          ports:
          - containerPort: 80
          volumeMounts:
          #   # - name: my-volume-storage
          #   #   mountPath: /var/data
            - name: my-volume-session
              mountPath: /var/lib/php/sessions
      # imagePullSecrets:
      #   - name: mysecret
      # volumes:
      #   - name: my-volume-storage
      #     persistentVolumeClaim:
      #         claimName: my-volume-claim
  volumeClaimTemplates:
  - metadata:
      name: my-volume-session
    spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Mi
        storageClassName: gp2
    